tilemap2= [
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                        ',
    'B...cB.....B.................B...cB       BBBBBB           ',
    'B....B.....B.................D....B       B....B           ',
    'B....B.....B.................B....B       B....B           ',
    'BBDBBBBBBDBB.................BBDBBBBBBBBBBBBB.BBBBBBBBBBBBB',
    'B............................B........e...................B',
    'BBDBBB.......................B............................B',
    'B....B.............e.........B....BBBBBBBBBBB.BBBBBB.BBBBBB',
    'B....B.......................B....B         B.B    B.B     ',
    'B....B.......................B....B         B.B  BBB.BBB   ',
    'BBBBBB.......................BBBBBB         B.B  B.....B   ',
    'B............................B              B.B  B.....B   ',
    'B..............P.............B     BBBBBBBBBBeB  BBBBBBB   ',
    'B........BBBDDBBB............B     B.......D..B            ',
    'B........B......B............B     B.BBBBBBBB.B            ',
    'B........B...e..B............B     B.B      B.B            ',
    'B........B......B............B     B.B      B.B            ',
    'B........BBBBBBBB............B     B.B      B.B            ',
    'B............................B     B.B      B.B            ',
    'B............................B     B.B      B.B            ',
    'B............................B     B.B      B.B            ',
    'B............................B   BBB.BBBBBBBBDBBB          ',
    'B.....e......................B   B......B...D...B          ',
    'B............................B   B......B.e.B...B          ',
    'B............................B   B......B...B...B          ',
    'B............................B   B......B...B...B          ',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB   BBBBBBBBBBBBBBBB          ',
]

tilemap1= [
    'BBBBBB                        ',
    'B...cB       BBBBBB           ',
    'B.P..B       B....B           ',
    'B....B       B....B           ',
    'BBDBBBBBBBBBBBBB.BBBBBBBBBBBBB',
    'B............................B',
    'BB.BBBBBBBBBBBBB.BBBBBB.BBBBBB',
    'B....B         B.B    B.B     ',
    'B....B         B.B    B.B     ',
    'B....B         B.B  BBB.BBB   ',
    'BBBBBB         B.B  B.....B   ',
    '               B.B  B.....B   ',
    '      BBBBBBBBBB.B  BBBBBBB   ',
    '      B.......D..B            ',
    '      B.BBBBBBBB.B            ',
    '      B.B      B.B            ',
    '      B.B      B.B            ',
    '      B.B      B.B            ',
    '      B.B      B.B            ',
    '      B.B      B.B            ',
    '      B.B      B.B            ',
    '    BBB.BBBBBBBBDBBB          ',
    '    B......B...D...B          ',
    '    B......B...B...B          ',
    '    B.B....D...B...B          ',
    '    B.B....B...B...B          ',
    '    BBBBBBBBBBBBBBBB          ',
]
